### PR TITLE
Save nginx health checks to a local file

### PR DESCRIPTION
**Pull request by karan**
R: @andrewsg 

This is done so we can report aggregate stats for health check statuses.

### CODE REVIEW

**Comment by andrewsg** [comment]
Does this swallow health checks in a way that prevents them from reaching the normal logging destination?

**Comment by karan** [comment]
It does not. 

image

**Comment by karan** [comment]
Just to be safe, I forked the nginx health check stream into a copy and save that to a file. Further, I flush the buffer every other minute.

**Comment by karan** [comment]
Yes been testing it manually and no the _copy log doesn't appear in Cloud Logging.

For testing I deployed a flex app, SSH'd into a VM, copied the scripts to the vm_runtime directory and this fluentd config patch, then started a cron to log the health check aggregate stats.

**Pull request merged**
