### PR TITLE
Allow ESP integration

### PR DESCRIPTION
**Pull request by kmbarry1**
Changes to enable integration of the IAP JWT verification module into ESP. This includes:
* Move WORKSPACE file to top-level directory (this triggers include path modifications)
* Add a .bzl file to allow consumers to easily pull in dependencies
* Top-level build file to define overarching package
* Use Apache license for files now outside of third_party

### CODE REVIEW

**Comment by rdcastro** [comment]
Added reviewers.

**Comment by kmbarry1** [comment]
* rebased (never done that before, I...I can't believe it actually worked).
* description updated (in addition to what you called out, there's also an added .bzl file)
* changed license to Apache for everything that was moved out of third_party

**Comment by drewinglis** [comment]
Just to clarify: what is the benefit of moving jsoncpp.BUILD to the repository root? It's only needed for the iap_jwt_verify_nginx module, right?

**Comment by kmbarry1** [comment]
Basically it's so consumers can compile the iap_jwt_verify_nginx module more easily. This kind of construct is standard practice in Bazel, see e.g. https://nginx.googlesource.com/nginx/+/master/build.bzl.

It will seem more natural once we move the iap_jwt_verify_nginx module to its own repo.

It may also help you to look at how the integration is done; see latest commits to https://github.com/kmbarry1/esp.

**Pull request merged**
