### PR TITLE
Remove misleading error message with service bridge

### PR DESCRIPTION
**Pull request by shantuo**
Regarding to #82 , this removes the misleading part of the error message.

### CODE REVIEW

**Comment by Cynocracy** [comment]
What's confusing about the second part of the error message, exactly?

**Comment by shantuo** [comment]
We have customer setting this that got deployment error.

**Comment by Cynocracy** [comment]
Ah interesting, they should be informed if that setting is being silently ignored, that sounds like a bug on our end.

**Comment by drewinglis** [comment]
To me it sounds like they're getting a deployment error because we don't allow them to set this beta setting. @shantuo, can you clarify what error they're getting?

**Comment by shantuo** [comment]
Sure, cc'ed you in the bug. It was a suppression method provided by us along with the "internal.flushLog" error message.

**Comment by yanweiguo** [comment]
Close this since no updates for a year.

**Pull request closed without merging**
