### PR TITLE
Add nginx access logs, with support for traceId if found.

### PR DESCRIPTION
**Pull request by andrewsg**
R: @apolito CC: @dlorenc @liqianluo

### CODE REVIEW

**Comment by andrewsg** [comment]
@apolito PTAL

**Comment by andrewsg** [comment]
This version will capture all access logs including health checks; even if it passes review let's hold off on merging until we've decided for sure that's what we want. We might have to add logic to filter them out.

**Comment by andrewsg** [comment]
We've decided NOT to filter out health checks at this time, so that's no longer an issue.

**Comment by apolito** [comment]
lgtm?  as lgtm as that regex can ever get?

**Comment by andrewsg** [comment]
Renamed the stream from "nginx.access" to just "access" and squashed the commit. Merging.

**Pull request merged**
