### PR TITLE
Enable JSON detection in text logs.

### PR DESCRIPTION
**Pull request by igorpeshansky**
Fixes https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/89.

### CODE REVIEW

**Comment by igorpeshansky** [comment]
@andrerod @Cynocracy can you please take a look?

**Comment by meltsufin** [comment]
Friendly ping. @andrerod

**Comment by drewinglis** [comment]
Can you elaborate on what this option does, and if there are any potential performance implications?

**Comment by igorpeshansky** [comment]
@drewinglis This option will cause the logging agent to attempt parsing any string that starts with a '`{`' (modulo whitespace) as JSON, and send the contents as a structured payload if the parse succeeds. The performance implication is if the logs contain many long strings that are invalid JSON (the parse effort will be wasted). For reference, GKE had this turned on by default since 2016, and there were no complaints.

**Comment by drewinglis** [comment]
Presumably it takes more computational resources to process a log line as JSON than to process it as plain text, though. Do you have numbers to show how much more expensive it will be?

**Comment by igorpeshansky** [comment]
@drewinglis No, we don't have any, but the code first short-circuits through each line until it finds a non-whitespace character, and only if it's a '`{`' does it parse JSON. So only the legitimate JSON lines will be parsed.

**Comment by drewinglis** [comment]
To clarify, my concern here is that this will be computationally expensive even when the JSON is legitimate. fluentd already has a very large resource footprint, and I'm hesitant to blindly enable something that will increase that, which is why I asked if you have any performance numbers.

**Comment by igorpeshansky** [comment]
Understood. Unfortunately, we don't have any numbers, but GKE is also very sensitive to fluentd resource usage, and they found the cost acceptable.

**Comment by drewinglis** [comment]
I ran some performance tests on this today and I think the performance hit is acceptable. (My test app peak QPS was about 20-30% lower.)

**Comment by gciotta** [comment]
I'd like to test this change with our applications. Do you know if it's possible to force the provisioning of a GAE flex managed VM with it?

In the meantime, I'm trying to see if I can make it work by changing the fluentd config by hand and stopping/starting the fluentd-logger container within the managed VM. Even with `detect_json true`, I'm unable to get my logs recognized.

I'm printing to stdout and stderr log records with the following format:

```json
{
  "message": "my message",
  "severity": "DEBUG"
}
```
My understanding is that the `timestamp` field (with seconds and nanoseconds) should be filled up by `out_from_docker.rb`

Unfortunately, they still show up unparsed (as `textPayload`). Is there anything else, or maybe some other required field to take into account?

The full record looks like this:

```
{
 insertId:  "27wss9g11lfwdd"  
 labels: {
  appengine.googleapis.com/instance_name:  "aef-logthis-20180208t112049-hfgw"   
  compute.googleapis.com/resource_id:  "[snip]"   
  compute.googleapis.com/resource_name:  "[snip]"   
  compute.googleapis.com/zone:  "europe-west1-c"   
 }
 logName:  "projects/[snip]/logs/appengine.googleapis.com%2Fstderr"  
 receiveTimestamp:  "2018-02-08T10:33:21.236356904Z"  
 resource: {
  labels: {
   module_id:  "logthis"    
   project_id:  "[snip]"    
   version_id:  "20180208t112049"    
  }
  type:  "gae_app"   
 }
 textPayload:  "{"message": "*** Debugging ***", "severity": "DEBUG"}
"  
 timestamp:  "2018-02-08T10:33:20Z"  
}
```

**Comment by igorpeshansky** [comment]
@gciotta JSON detection only works if the whole object is on a single log line.

**Comment by gciotta** [comment]
@igorpeshansky the message is actually printed to stdout on a single line. I pretty-printed it in the first example just to highlight the fields. The "textPayload" field of the raw log record contains everything I'm sending to stdout, which is a single line.

On related note, the log viewer inserts a spurious newline before the closing quotation marks in `textPayload` (it happens with every message containing a textPayload, even in other applications with no json logging).

**Comment by meltsufin** [comment]
I think the issue is that the change hasn't rolled out yet in the Flex VM image.

**Comment by igorpeshansky** [comment]
Oh. If the change hasn't rolled out, then your agent doesn't have the necessary code and won't recognize the option. That would explain why it's not parsing the JSON.

If you just want to see it work, you could install the latest agent on a GCE VM and try it out.

**Comment by gciotta** [comment]
Thanks, now everything makes sense :smile: 

We're currently choosing between logging JSON to stackdriver using 1) `google-cloud-logging` or 2) stdout/stderr with the fluentd agent. We like 2) more because of its simplicity. Do you know when the updated package would likely be available in the Flex VM image? That would help us pick between the two solutions.

Thanks!

**Comment by drewinglis** [comment]
This release should finish rolling out by EOD today.

**Comment by gciotta** [comment]
FYI we just deployed (a couple of hours ago) a few Flex VMs and the fluentd-logger image appears to be 20180129-rc00, which doesn't feature the `detect_json` param in `managed_vms.conf`

**Comment by drewinglis** [comment]
Hmm, it looks like this didn't make the cut for the 0129 release, so it will roll out this week. If you want, we can whitelist you to get the new image early. If you're interested, please email your GCP project id to <my Github username>@google.com.

**Comment by gciotta** [comment]
We had to apply make a small change to `fluentd_logger/out_from_docker.rb` to get everything working (after enabling the beta VM image).

The issue seems to be that [`out_from_docker.rb#L33`](https://github.com/GoogleCloudPlatform/appengine-sidecars-docker/blob/master/fluentd_logger/out_from_docker.rb#L33) sets a `timestamp` key, which is not popped out of the log record hash by [`fluent-plugin-google-cloud/lib/fluent/plugin/out_google_cloud.rb#L517`](https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/master/lib/fluent/plugin/out_google_cloud.rb#L517), which is expecting a key named `time`.
Since the key is not deleted, the hash will have length > 1, and it [won't be decoded](https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/master/lib/fluent/plugin/out_google_cloud.rb#L523), even if it's valid json.

Once we applied [this oneliner](https://github.com/ticketea/appengine-sidecars-docker/commit/d9e80484312b21dfb3c32bd51fe71e5661249ff2), logs started to be parsed correctly. However, given the amount of moving parts, I'm not sure if this is the right thing to do, or the implications of the change.

I've put up a [one-file Django application](https://github.com/ticketea/logthis) which runs under GAE flex and logs JSON messages in response to health checks, which can be useful to reproduce the issue. If this application runs in combination with the change above, I've verified that logs are parsed and correctly shown in the log viewer.

**Comment by igorpeshansky** [comment]
@gciotta, this could also have been done by rewriting the record in a filter in the fluentd configuration. But yeah, better to fix `out_from_docker.rb`...

**Comment by drewinglis** [comment]
Is `timestamp` exposed to users anywhere downstream of this? If so, I don't think we can rename it to `time`, as that would break any existing users depending on this behavior.

Can the fluentd plugin behavior be changed to treat `time` and `timestamp` the same?

**Comment by igorpeshansky** [comment]
Not today: https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/4.

**Comment by drewinglis** [comment]
Let me clarify: can we change https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/master/lib/fluent/plugin/out_google_cloud.rb#L517 to special-case both `timestamp` and `time`?

**Comment by igorpeshansky** [comment]
I suspect that's likely to break users who would be relying on the current behavior of `timestamp` being ignored (retained in the payload). Unfortunately, we have no way to know if such users exist.
IMO, the best bet would be to make this configurable and set it up appropriately for GAE Flex.

**Comment by gciotta** [comment]
It looks like the `timestamp` information is not currently retained in the textPayload. I'm not sure there's a way to rely on this field. There is a top-level `timestamp` which is inserted regardless of the change.

This is a log entry without the `out_from_docker.rb` change:

logs_not_working

This is a log entry from the same app once the `out_from_docker.rb` [change](https://github.com/ticketea/appengine-sidecars-docker/commit/d9e80484312b21dfb3c32bd51fe71e5661249ff2) is applied. The `timestamp` handling doesn't seem affected:

logs_working

**Comment by igorpeshansky** [comment]
Never mind, I was being silly. @drewinglis is correct. There are multiple possible fields accepted by the timestamp computation code at https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/master/lib/fluent/plugin/out_google_cloud.rb#L1440 — we should be prepared to encounter any of them in the JSON detection code at https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/master/lib/fluent/plugin/out_google_cloud.rb#L517.
@gciotta, could you please open an issue against https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud and reference this thread? We'll fix it. Unfortunately, it will require another build and rollout of this image once the fix is released.

**Comment by colinmarc** [comment]
Hi, how do you enable this for the App Engine Flexible environment? My JSON logs are still being copied into `textPayload` on my app, and they are definitely single-line json.

**Pull request merged**
